workflows:
  android-workflow:
    name: Build 3dspot APK
    max_build_duration: 30
    environment:
      groups:
        - spotify_keys
    scripts:
      - name: Build APK
        script: |
          # Ahora que todo está en la raíz, no hace falta el 'cd'
          chmod +x gradlew
          
          # Reemplazamos el ID en la ruta correcta de la carpeta app
          sed -i '' "s/SPOTIFY_CLIENT_ID_PLACEHOLDER/$SPOTIFY_CLIENT_ID/g" app/src/main/java/com/galaxy/dspot/SpotifyManager.kt
          
          # Compilamos el APK
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
      
